import { StyleSheet, Dimensions } from 'react-native';

const CARD_MARGIN = 10;
const CARD_WIDTH = (Dimensions.get('window').width - CARD_MARGIN * 3) / 2;

export default StyleSheet.create({
  container: { flex: 1, backgroundColor: '#f6f8fa', paddingTop: 12 },
  header: {
    fontSize: 28,
    fontWeight: 'bold',
    color: '#1976d2',
    marginBottom: 10,
    marginLeft: 18,
    letterSpacing: 0.5,
  },
  searchBarWrapper: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#e3eafc',
    borderRadius: 12,
    marginHorizontal: 16,
    marginBottom: 12,
    paddingHorizontal: 12,
    paddingVertical: 6,
    elevation: 2,
  },
  searchBar: {
    flex: 1,
    fontSize: 16,
    color: '#1976d2',
    backgroundColor: 'transparent',
    borderWidth: 0,
    paddingVertical: 4,
  },
  listContent: {
    paddingHorizontal: CARD_MARGIN,
    paddingBottom: 80,
  },
  card: {
    backgroundColor: '#fff',
    borderRadius: 18,
    margin: CARD_MARGIN,
    flex: 1,
    elevation: 4,
    shadowColor: '#1976d2',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.13,
    shadowRadius: 8,
    overflow: 'hidden',
    maxWidth: CARD_WIDTH,
    minHeight: 220,
  },
  imageWrapper: {
    position: 'relative',
    width: '100%',
    height: 140,
    backgroundColor: '#e3eafc',
  },
  cardImage: {
    width: '100%',
    height: '100%',
  },
  overlay: {
    backgroundColor: 'rgba(25, 118, 210, 0.85)',
    padding: 10,
    borderBottomLeftRadius: 18,
    borderBottomRightRadius: 18,
  },
  cardTitle: {
    color: '#fff',
    fontWeight: 'bold',
    fontSize: 16,
    marginBottom: 2,
  },
  cardDate: {
    color: '#e3eafc',
    fontSize: 13,
    marginBottom: 2,
  },
  cardLocation: {
    color: '#fff',
    fontSize: 13,
    marginTop: 2,
    flexDirection: 'row',
    alignItems: 'center',
  },
  favoriteIcon: {
    position: 'absolute',
    top: 10,
    right: 10,
    zIndex: 2,
    backgroundColor: 'rgba(25, 118, 210, 0.7)',
    borderRadius: 16,
    padding: 2,
  },
  centered: { flex: 1, justifyContent: 'center', alignItems: 'center' },
  fab: {
    position: 'absolute',
    right: 22,
    bottom: 22,
    backgroundColor: '#1976d2',
    borderRadius: 32,
    width: 60,
    height: 60,
    alignItems: 'center',
    justifyContent: 'center',
    elevation: 8,
    shadowColor: '#1976d2',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 8,
  },
});